# Generated by Django 4.2.3 on 2023-07-10 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Analysis", "0004_remove_financialdata_data"),
    ]

    operations = [
        migrations.RenameField(
            model_name="financialdata",
            old_name="costos",
            new_name="rotacion_inventario",
        ),
        migrations.RemoveField(
            model_name="financialdata",
            name="precio_inventario_promedio",
        ),
    ]
