# Generated by Django 4.2.3 on 2023-07-11 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Analysis", "0005_rename_costos_financialdata_rotacion_inventario_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="indicatorvalue",
            name="Indicator_id",
        ),
        migrations.AddField(
            model_name="indicatorvalue",
            name="Indicator_id",
            field=models.ManyToManyField(to="Analysis.indicator"),
        ),
    ]
